### ISSUE TITLE
Error 'null' logging in: {"ReturnCode":"217"

### ISSUE THREAD

**Issue by jojo3632** [nfarina/homebridge-liftmaster#3] opened 2015-12-10 06:52 UTC
Hi,

I'm trying to get homebridge running to control my liftmaster garage door.
I was able to install homebridge. I'm able to launch homebridge, I can add the devide to the Insteon I downloaded. When I run homebridge, here is what I see:

*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see http://0pointer.de/avahi-compat?s=libdns_sd&e=node
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister
Loaded plugin: homebridge-liftmaster

Registering accessory 'homebridge-liftmaster.LiftMaster'

Loaded config.json with 1 accessories and 0 platforms.

Loading 1 accessories...
[Garage Door] Initializing LiftMaster accessory...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:

┌────────────┐
│ 031-45-154 │
└────────────┘
Homebridge is running on port 51826.
[Garage Door] Error 'null' logging in: {"ReturnCode":"217","ErrorMessage":"Error processing request (217)","CorrelationId":"e1c904f0-a8ae-4ec2-92e9-5424245db3c2"}

But as soon as I try to operate the door via the app or Siri, I get this error:

[Garage Door] Error 'null' logging in: {"ReturnCode":"217","ErrorMessage":"Error processing request (217)","CorrelationId":"e1c904f0-a8ae-4ec2-92e9-5424245db3c2"}

Can you help?
Jojojo3632

**Comment by jojo3632** [comment] 2015-12-10 21:01
I was able to make some progress but still need help.

I was able to directly trigger API replies using a different APPID than the one used in the index.js.

When I use https://myqexternal.myqdevice.com/Membership/ValidateUserWithCulture?appId="Vj8pQggXLhLy0WHahglCD4N1nAkkXQtGYpq2HrHD7H1nvmbT55KqtN6RSF4ILB%2fi"&securityToken=null&username="my_username_edited-here"&password="my_password-edited here"&culture=en

I'm able to get my SecurityToken. 

Similarly, when I use https://myqexternal.myqdevice.com/api/UserDeviceDetails?

When I use this APPID in the homebridge-liftmaster index.js, I get a different error now:

[Garage Door] Logged in with user ID undefined
_http_outgoing.js:333
    throw new Error('`value` required in setHeader("' + name + '", value).');
    ^

Error: `value` required in setHeader("SecurityToken", value).
    at ClientRequest.OutgoingMessage.setHeader (_http_outgoing.js:333:11)
    at new ClientRequest (_http_client.js:80:14)
    at Object.exports.request (http.js:31:10)
    at Object.exports.request (https.js:163:15)
    at Request.start (/usr/local/lib/node_modules/homebridge-liftmaster/node_modules/request/request.js:914:30)
    at Request.end (/usr/local/lib/node_modules/homebridge-liftmaster/node_modules/request/request.js:1728:10)
    at end (/usr/local/lib/node_modules/homebridge-liftmaster/node_modules/request/request.js:704:14)
    at Immediate._onImmediate (/usr/local/lib/node_modules/homebridge-liftmaster/node_modules/request/request.js:718:7)
    at processImmediate [as _immediateCallback] (timers.js:371:17)

Could it be that the parsing of the userID and other values are different?
My programming skills are very limited. So any help would be great!

Thank you,
Jojojo3632

**Comment by AppleTechy** [comment] 2015-12-15 00:54
I am having the same issue @jojo3632 Have you gotten it to work yet? Thanks, Appletechy

**Comment by jojo3632** [comment] 2015-12-15 04:53
Hi Appletechy. No. no news.I originally posted on the main homebridge issue board, Nfarina quickly replied and asked me to post here. Since then, not a word.

**Comment by nfarina** [comment] 2015-12-17 19:17
Hey guys - I'm really stumped here unfortunately. The plugin still works well for me so I can't reproduce the issue. @jojo3632 Your results look promising, did you attempt to change the `APP_ID` directly in `index.js` and try again?

**Comment by AppleTechy** [comment] 2015-12-18 05:15
So MYQ app update was pushed out today… I haven’t had any new luck I am still getting a 500 internal server error as well as the 217 error. Please keep me updated… I am welling to try fixes if you think  of  anything. @jojo3632 Me and @nfarina looked into charles to find out what the actually server error was(500 server) Could u send them to me and nfarina on slack, of course with passwords and personal info excluded from it? This way we can determine if we both are having the exact same issue and if you data gives us an more clues to what the problem is... Thanks, Apple T.

**Comment by AppleTechy** [comment] 2015-12-18 18:29
Ok so I got further than before @nfarina . I received the same result as @jojo3632 So I got 

Garage Door] Logged in with user ID undefined
_http_outgoing.js:333
    throw new Error('`value` required in setHeader("' + name + '", value).');
    ^

Error: `value` required in setHeader("SecurityToken", value).
    at ClientRequest.OutgoingMessage.setHeader (_http_outgoing.js:333:11)
    at new ClientRequest (_http_client.js:80:14)
    at Object.exports.request (http.js:31:10)
    at Object.exports.request (https.js:163:15)
    at Request.start (/usr/local/lib/node_modules/homebridge-liftmaster/node_modules/request/request.js:914:30)
    at Request.end (/usr/local/lib/node_modules/homebridge-liftmaster/node_modules/request/request.js:1728:10)
    at end (/usr/local/lib/node_modules/homebridge-liftmaster/node_modules/request/request.js:704:14)
    at Immediate._onImmediate (/usr/local/lib/node_modules/homebridge-liftmaster/node_modules/request/request.js:718:7)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

I received this after only changing the app id to "Vj8pQggXLhLy0WHahglCD4N1nAkkXQtGYpq2HrHD7H1nvmbT55KqtN6RSF4ILB%2fi" 
I found this id through http://docs.unofficialliftmastermyq.apiary.io/#introduction/constant-values
I have little coding experience as we have already discussed @nfarina , can u look at this unofficial api guide and possible draft a modified index.js for it if this isn't what it already is based off of? Thanks, Apple T.

**Comment by brycedhall** [comment] 2015-12-19 04:15
I'm getting the same error as everyone else.

[Garage Door] Error 'null' logging in: {"ReturnCode":"217","ErrorMessage":"Error processing request (217)","CorrelationId":"XXXXXXXXXXXX"}

**Comment by nfarina** [comment] 2015-12-19 17:26
The message `Logged in with user ID undefined` implies that we are receiving a different response from the login request than was expected. Can you paste the exact JSON response received from the server when you access the `validateuserwithculture` URL?

**Comment by brycedhall** [comment] 2015-12-19 17:33
I am talking way over my head here, but this is what I did, and what I got:

Input url:
http://myqexternal.myqdevice.com/Membership/ValidateUserWithCulture?appId=Vj8pQggXLhLy0WHahglCD4N1nAkkXQtGYpq2HrHD7H1nvmbT55KqtN6RSF4ILB%2fi&securityToken=null&username=XXXXXXXX&password=XXXXXXXX&culture=en



Message received:
{"UserId":0,"SecurityToken":"XXXXXXXXXXXX","ReturnCode":"0","ErrorMessage":"","BrandId":2,"BrandName":"Chamberlain","RegionId":1}

**Comment by nfarina** [comment] 2015-12-19 17:39
@brycedhall That is very promising - can you try modifying `index.js` from your _installed_ copy of `homebridge-liftmaster` (located somewhere like `/usr/local/lib/node_modules/homebridge-liftmaster/index.js`) and change this line:

```js
var APP_ID = "Vj8pQggXLhLy0WHahglCD4N1nAkkXQtGYpq2HrHD7H1nvmbT55KqtN6RSF4ILB/i"
```

That _should_ cause it to issue a request exactly like the one that's working for you.

**Comment by brycedhall** [comment] 2015-12-19 18:02
After changing the APP_ID, I'm still getting the original error message in terminal:

[Garage Door] Error 'null' logging in: {"ReturnCode":"217","ErrorMessage":"Error processing request (217)","CorrelationId":"1b335e14-6a3e-49c5-89ab-bbcd2bde2f37"}

**Comment by nfarina** [comment] 2015-12-19 18:43
That is really strange. It still works for me with the changed APP_ID.

If anyone is willing to change their MyQ password for a period of a few hours and email it to me, it would be extremely helpful. Right now I just can't figure out how to reproduce the issue so I am shooting in the dark with my attempts to fix it.

**Comment by brycedhall** [comment] 2015-12-19 19:51
I'll play with it a bit.

Found this, doesn't really seem to have a resolution: https://myqcommunity.chamberlain.com/chamberlainmyq/topics/error-217

**Comment by brycedhall** [comment] 2015-12-19 20:23
@AppleTechy / @jojo3632  any progress on your ends?

**Comment by AppleTechy** [comment] 2015-12-19 22:06
Ok I don't know what I did but now I am receiving the error 
Error 'Error: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:8888' logging in: undefined
I believe I screwed something up yesterday so I am going to reinstall the plugin and see if I now receive the same error message above..
\

**Comment by AppleTechy** [comment] 2015-12-19 22:19
Ok. @nfarina @jojo3632 @brycedhall  What os are u running this on?

**Comment by brycedhall** [comment] 2015-12-20 02:19
@AppleTechy OS X. Older computer running 10.10 (14A299l)

**Comment by AppleTechy** [comment] 2015-12-20 02:30
Ok I am running OS X I am wondering if it is a problem with the networking on Mac... Just trying to maybe determine if that is the issue

**Comment by AppleTechy** [comment] 2015-12-29 00:25
Succes! With talking to @nfarina we discovered the problem! The issue is rooted in my config.json not my Index.js for the plugin. If you go into your config look at how you inputed your username and password into the accessory. If you still have arrow brackets around you username and password, like {
    "accessory": "LiftMaster",
    "name": "Garage Door",
    "username": "<applegeek@geek.com>",
    "password": "<Test123>"
    }
The issue is that it should look like this{
    "accessory": "LiftMaster",
    "name": "Garage Door",
    "username": "applegeek@geek.com",
    "password": "Test123"
    }
Now if you look the arrow brackets are gone. As long as everything else if formatted correctly you shouldn't have a problem. If any of you are using Textedit steer clear if will mess-up all your formatting! I am currently using atom.io and it actually tells you where the issue is in you formatting if you make a mistake. 
If you are still having the 217 error let me or @nfarina know and we can look into the problem.
Best of luck, Apple T.

**Comment by jojo3632** [comment] 2015-12-30 17:52
Hi AppleT, Nfarina,

Glad you were able to finally make it work.
But still no luck for me. I'm not getting the 217 error though, I'm getting this now: "Error 'Error: read ECONNRESET' logging in: undefined" error, on and on and on.

So a couple of questions:
1. I don't see a difference between your to config.json examples above. Here is mine (edited  MAC address, user name and password), is this how it should be 

        "bridge": {
                "name": "Homebridge",
                "username": "00:01:01:01:15:CD",
                "port": 51826,
                "pin": "111-11-111"
        },

        "description": "This is an example configuration file with one fake accessory and one fake p$

        "accessories": [
                {
                "accessory": "LiftMaster",
                "name": "Garage Door",
                "username": "myemail@address",
                "password": "my_password"
}
        ]
}

2. Did you revert back to the original index.js or did you keep the new app-ID?

Thanks,
J.

**Comment by AppleTechy** [comment] 2015-12-30 20:03
@jojo3632 Sorry Github thought I was trying to format something so it hide the characters that make the difference in my examples. Thank you for bringing that to my attention I fixed my earlier post. I ended up reverting back to the original index.js that was supplied with the plugin.( I later edited it to add the status fix for multiple garage doors.) As for the EconRest error do you have any other plugins installed? I believe you have fixed the garage door and that error is related to a different plugin you have installed.....

**Comment by jojo3632** [comment] 2016-01-02 18:30
@AppleTechy 
Thanks for the clarification. Some progress but no cigar yet! I'm not using any other plugin.
I don't get any error 333 or 217 anymore. But I get this:
[Garage Door] Logged in with user ID 0
[Garage Door] Error: Couldn't find a door device, or the ID you specified isn't associated with your account

I'm using the username and password to log in to https://www.myliftmaster.com/ which enables me to control my garage door through a browser.

When I manually initiate the query with https://myqexternal.myqdevice.com/Membership/ValidateUserWithCulture?appId=Vj8pQggXLhLy0WHahglCD4N1nAkkXQtGYpq2HrHD7H1nvmbT55KqtN6RSF4ILB%2f...
I get a valid security token so I know I'm using the right credentials

J.

**Comment by AppleTechy** [comment] 2016-01-03 01:13
@jojo3632 try reinstalling the plugin not just switching out the index.js. Then try

**Comment by jojo3632** [comment] 2016-01-03 17:31
Thanks for your help on this.

I reinstalled the liftmaster plugin.
Now, I can't even add my device on Insteon.
It takes many tries to even see the homebridge deleting the /persist directory and/or changing the bridge user name (MAC address) then it times out.
This is frustrating! I think I need to do this from scratch.
I'll do that another day and will let you know how things work out.

J.

**Comment by AppleTechy** [comment] 2016-01-03 17:36
@JoJo3632 All you should need to do is delete the persist folder. Then using Insteon+ delete you home and verify that it has removed all the devices from you home... Then try repairing you homebridge to Insteon+

**Comment by AppleTechy** [comment] 2016-01-04 04:32
@jojo3632 what os are you running on? Mac, Linux, or Windows? Just trying to understand what you were saying about changing the MAC address or deleting the /persist directory.... On OS X I don't have a problem with any of that.

**Comment by jojo3632** [comment] 2016-01-04 17:39
Raspian Linux on a Pi 2.The MAC address change trick is listed in your homebridge readme.md instructions, towards the end in the "Why iOS App Can't Find Homebridge" section.

**Comment by AppleTechy** [comment] 2016-01-04 20:37
@jojo3632 Where you able to add your home bridge? If not I am sorry but I can't be much of assistants as I am running on mac. But when mine stops working all I do is end homebridge and then go in a delete my /persist directory and then restart homebridge. Make sure you are connected to the same network otherwise HomeKit apps will not be able to pick up homebridge as an accessory therefore not allowing you to connect. Good luck and keep me update.

**Comment by AppleTechy** [comment] 2016-01-10 05:24
@jojo3632 Have you had any success in the last couple of days?

**Comment by jojo3632** [comment] 2016-01-11 19:40
Thanks for checking in.
Unfortunately not yet.

**Comment by AppleTechy** [comment] 2016-01-12 02:50
So I forget is your homekit running correctly with no errors but you can't seem to get it to connect to the iOS device?@jojo3632

**Comment by jojo3632** [comment] 2016-01-25 03:19
SUCCESS!!!
I think the breakthrough came from having the right config.json and resetting homekit on iphone: Settings -> Privacy (not, as one would assuming, to Settings -> HomeKit).

I can finally control my garage door via Siri. Very cool.
Thank you for your help and patience!

Now, one quick question. 
I'm not able to control my door via Siri when I'm not on my home wifi. This would be useful when I'm in my car coming home for example. I tried connecting to my home network via VPN. That gives me a local IP address on my home network. So that should theortically work. Is there some port forwarding setting to add? To my server running homebridge? To my myQ device?

**Comment by nfarina** [comment] 2016-01-25 04:07
@jojo3632 Remote control via Siri is possible but requires Apple TV. If you have one, it should "just work" as they say.

**Comment by AppleTechy** [comment] 2016-02-07 21:41
@jojo3632 @nfarina Is it ok to close this?

**Comment by jojo3632** [comment] 2016-02-07 22:02
Hi AppleTechy,

Yes. OK to close.
Thank you for all your help!

J.

**Comment by AppleTechy** [comment] 2016-02-07 22:04
@jojo3632 Glad to hear you got it working!

**Closed** 2016-02-07 22:20 UTC
