### ISSUE TITLE
Multiple Garage Doors

### ISSUE THREAD

**Issue by sonnie001** [nfarina/homebridge-liftmaster#7] opened 2015-12-31 20:13 UTC
I am attempting to get 2 garage doors configured and am hitting a wall.    The error message received is:

[Single Garage Door] Logged in with user ID 0
[Single Garage Door] WARNING: You have multiple doors on your MyQ account.
[Single Garage Door] WARNING: Specify the ID of the door you want to control using the 'requiredDeviceId' property in your config.json file.
[Single Garage Door] WARNING: You can have multiple liftmaster accessories to cover your multiple doors
[Single Garage Door] Found Door: 1572446 - Double Door
[Single Garage Door] Found Door: 1572447 - Single Door

The Section for myq in my config.json is:

{
			"accessory": "LiftMaster",
			"name": "Double Garage Door",
			"username": "xxxx@xxxx.com",
			"password": "xxxxxx",
			"deviceID": "1572446-Double Door"
		}, {
			"accessory": "LiftMaster",
			"name": "Single Garage Door",
			"username": "xxxxx@xxxx.com",
			"password": "xxxxxx",
			"deviceID": "1572447-Single Door"
		}

I am not getting any errors on launching home bridge until I go to access one of the doors. 

Any directions to move past this?  I suspect I have entered the syntax of the device ID wrong. 

Cheers

**Comment by AppleTechy** [comment] 2015-12-31 20:15
The issue is that you need to change "deviceId" to "requireddeviceId". This should fix your problem

**Comment by danoday** [comment] 2015-12-31 20:19
Not sure if it is case sensitive, but use "requiredDeviceID" instead of (or in addition to, if you like) "deviceID".

Also, just use the numeric portion of the deviceID.  Remove the "-Single Door" and "-Double Door" parts.  I don't think those are part of the deviceID itself, only the appended description.

**Comment by sonnie001** [comment] 2015-12-31 20:25
Thanks for the quick responses dandy and AppleTechy...    I have modified as suggested, so now my config.json section reads as:

{
			"accessory": "LiftMaster",
			"name": "Double Garage Door",
			"username": "xxx@xxxx",
			"password": "xxxx",
			"requiredDeviceID": "1572446"
		}, {
			"accessory": "LiftMaster",
			"name": "Single Garage Door",
			"username": "xxxx",
			"password": "xxxxx",
			"requiredDeviceID": "1572447"
		}

I am getting the same error in home bridge when accessing the accessories from Insteon+.   Now my openers are Chamberlain , not lift master, but I can access the MyQ account through Liftmaster so didn't think that would matter.

**Comment by danoday** [comment] 2015-12-31 20:28
Hmm... have you stopped and restarted Homebridge from the command line.  I don't think it recognizes config.json changes until reload.

**Comment by sonnie001** [comment] 2015-12-31 20:31
danoday...  the error that is generated from accessing the door accessory crashes Homebridge with:

/usr/local/lib/node_modules/homebridge-liftmaster/index.js:147
          throw "FATAL: Please specify which specific door this Liftmaster accessory should control - you have multiples on your account";
          ^
FATAL: Please specify which specific door this Liftmaster accessory should control - you have multiples on your account

so I have restarted Homebridge with the new config.json but with the same result

**Comment by AppleTechy** [comment] 2015-12-31 20:39
When did you install the plugin? Me and Nfarina updated the plugin about 2 days ago....

**Comment by sonnie001** [comment] 2015-12-31 20:40
I installed the plugin today, about 2 hours ago.

**Comment by danoday** [comment] 2015-12-31 20:42
Line 147 is a manual abend if it finds multiple doors without a device ID being specified.  It shouldn't even be hitting that code in your situation.

I might have had the variable wrong - try "requiredDeviceId" with a lower-case "D" at the end, not "requiredDeviceID" with an upper-case "D".  Restart and see if that helps.

**Comment by AppleTechy** [comment] 2015-12-31 20:47
The variable should read "requiredDeviceId" the should solve your problems. Save that, quit terminal and then try reloading homebridge. I believe that should be the correct variable. Or it might be DeviceId but the capitalization does matter! Wish I could be more help on what I have the variable set but I am not in front of my computer right now. Let me know if that works.

**Comment by sonnie001** [comment] 2015-12-31 20:50
I have updated the config.json with "requiredDeviceId" and that seams to have fixed the error!  Thanks guys!.   I shall now play with it and see how it performs before rolling out to my wife.

**Comment by AppleTechy** [comment] 2015-12-31 20:53
The only issue I have is Siri won't allow you to open/close one of the doors. She makes you close/open all of the doors. Let me know if that is the same case for you. You might just end up removing the single garage bay door that I never use. So that way Siri's voice command function with HomeKit is useful with my garage door. Thxs.

**Comment by danoday** [comment] 2015-12-31 21:01
@sonnie001 - Great news!  You might look at issue #6, and insert the code there to get the door status reporting correctly through Siri.

@AppleTechy - I can help with your Siri problem.  Siri defaults each garage door to a Siri name of "Garage Door", instead of "Big Garage Door" and "Small Garage Door"... or whatever you called them.  This makes Siri confused about which one you are referring to, and she wants to close/open both.  To change this, look for the "Service Name" in an app, which isn't necessarily the "Accessory Name".  If you download the Insteon+ app, you'll find this under "Siri Control" when you edit the device.

Let me know if that works.

**Comment by sonnie001** [comment] 2015-12-31 21:45
@danoday silly question (likely!)   where is the index.js file located?

**Comment by AppleTechy** [comment] 2015-12-31 21:53
It is located at /usr/local/lib/node_modules/homebridge-LiftMaster
Good luck! @Danoday thank you. I had been using the HM catalog app supplied by Apple for when I was setting up homebridge. I recently downloaded Insteon+ and fixed my problem

**Comment by AppleTechy** [comment] 2016-01-03 01:09
resolved

**Comment by AppleTechy** [comment] 2016-01-03 01:10
close #7

**Comment by danoday** [comment] 2016-01-03 01:14
I don't know that we should close this quite yet.  The "requiredDeviceId" thing really needs to be either changed in the code, or altered in the documentation before this issue is truly "closed"... otherwise, people will be opening a new issue for it every time.

Maybe we should create an issue titled "Variable deviceId is incorrect; please use requiredDeviceId instead".

**Comment by AppleTechy** [comment] 2016-01-03 01:21
@danoday i will message @nfarina asking him to change the documentation

**Comment by nfarina** [comment] 2016-01-06 21:57
Hey all, sorry about this, this happened because I used a README I created while I was working on a rewrite of this plugin, but then when it was taking too long I pasted in the old code.

I fixed `index.js` to use the correct parameter - `deviceID`.

**Closed** 2016-01-06 21:56 UTC
